[build]
  publish = "public"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  publish = "public"
  command = "remix watch"
  port = 3000

[context.dev]
  environment = { NODE_ENV = "development" }

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
